export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const UPDATE_WORKTIME = "UPDATE_WORKTIME";
export const UPDATE_BREAKTIME = "UPDATE_BREAKTIME";
export const UPDATE_ITERATIONS= "UPDATE_ITERATIONS";
export const UPDATE_PAGE = "UPDATE_PAGE";
export const UPDATE_TOTALTIME = "UPDATE_TOTALTIME";
export const UPDATE_TIMEREMAIN = "UPDATE_TIMEREMAIN";
export const UPDATE_TIMEACTIVE = "UPDATE_TIMEACTIVE";
export const UPDATE_ITERATIONS_REMAIN = "UPDATE_ITERATIONS_REMAIN";
export const UPDATE_JOKE = "UPDATE_JOKE";
export const UPDATE_GIF = "UPDATE_GIF";




export const UPDATE_UUID = "UPDATE_UUID";
